
package dkstatus.ui;

import dkstatus.world.Village;
import java.util.List;

/**
 *
 * @author Johny
 */
public class GameMapPanel extends javax.swing.JPanel {

    private final Village village;
    private List<Village> worldVillages;
    
    /**
     * Creates new form GameMap
     * @param village
     */
    public GameMapPanel(Village village) {
        this.village = village;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    void updateVillages(List<Village> villages) {
        worldVillages = villages;
        
        
    }

}
