/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dkstatus.ui;

import dkstatus.world.Player;
import dkstatus.world.Village;
import dkstatus.world.World;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;

/**
 *
 * @author Johny
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpVillages = new javax.swing.JTabbedPane();
        pPlayer = new javax.swing.JPanel();
        lblPlayer = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        lblPointCount = new javax.swing.JLabel();
        lblAnnounce = new javax.swing.JLabel();
        tbToolbar = new javax.swing.JToolBar();
        mbMenu = new javax.swing.JMenuBar();
        mSettings = new javax.swing.JMenu();
        mBrowser = new javax.swing.JMenu();
        rbmiChrome = new javax.swing.JRadioButtonMenuItem();
        rbmiFirefox = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DK Status");

        lblPlayer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPlayer.setText("Hráč:");

        lblPointCount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/wheel.png"))); // NOI18N
        lblPointCount.setText("0");

        lblAnnounce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/announce.png"))); // NOI18N
        lblAnnounce.setText("Oznámení");

        javax.swing.GroupLayout pPlayerLayout = new javax.swing.GroupLayout(pPlayer);
        pPlayer.setLayout(pPlayerLayout);
        pPlayerLayout.setHorizontalGroup(
            pPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPlayerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPlayerName)
                .addGap(128, 128, 128)
                .addComponent(lblPointCount)
                .addGap(58, 58, 58)
                .addComponent(lblAnnounce)
                .addContainerGap(682, Short.MAX_VALUE))
        );
        pPlayerLayout.setVerticalGroup(
            pPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPlayerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayer)
                    .addComponent(lblPlayerName)
                    .addComponent(lblPointCount)
                    .addComponent(lblAnnounce))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tbToolbar.setRollover(true);

        mSettings.setText("Settings");
        mbMenu.add(mSettings);

        mBrowser.setText("Browser");

        rbmiChrome.setSelected(true);
        rbmiChrome.setText("Chrome");
        mBrowser.add(rbmiChrome);

        rbmiFirefox.setSelected(true);
        rbmiFirefox.setText("Firefox");
        mBrowser.add(rbmiFirefox);

        mbMenu.add(mBrowser);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tpVillages)
            .addComponent(tbToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpVillages, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAnnounce;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblPointCount;
    private javax.swing.JMenu mBrowser;
    private javax.swing.JMenu mSettings;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JPanel pPlayer;
    private javax.swing.JRadioButtonMenuItem rbmiChrome;
    private javax.swing.JCheckBoxMenuItem rbmiFirefox;
    private javax.swing.JToolBar tbToolbar;
    private javax.swing.JTabbedPane tpVillages;
    // End of variables declaration//GEN-END:variables

    private final Map<Integer, VillagePanel> villagePanels = new HashMap<>();
    private final ImageIcon announceIcon = new ImageIcon(getClass().getResource("/resources/images/announce.png"));
    
    public void updateWindow(World world) {
        Player plr = world.getPlayer();
        
        lblPlayerName.setText(plr.getName());
        lblPointCount.setText(String.valueOf(plr.getPoints()));
        lblAnnounce.setIcon(plr.hasAnnounce() ? announceIcon : null);
        
        for (Village v : plr.getVillages()) {
            
            VillagePanel vp;
            if (!villagePanels.containsKey(v.getId())) {
                vp = new VillagePanel();
                villagePanels.put(v.getId(), vp);
                tpVillages.add(v.toString(), vp);
            } else {
                vp = villagePanels.get(v.getId());
            }
            
            vp.updateVillage(v);
        }
    }
}
