
package dkstatus.ui;

import dkstatus.world.Village;

/**
 *
 * @author Johny
 */
public class VillageTabsPanel extends javax.swing.JPanel {

    private final Village village;
    
    /**
     * Creates new form VillageTabsPanel
     * @param village
     */
    public VillageTabsPanel(Village village) {
        this.village = village;
        
        initComponents();
        
        info = new VillageMainPanel(village.getId());
        tpVillage.add("Informace", info);
        
        raid = new RaidHelperPanel(village);
        tpVillage.add("Rabování", raid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpVillage = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpVillage, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpVillage, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tpVillage;
    // End of variables declaration//GEN-END:variables

    private final VillageMainPanel info;
    private final RaidHelperPanel raid;
    
    public Integer getId() {
        return village.getId();
    }
    
    VillageMainPanel getVillagePanel() {
        return info;
    }

    RaidHelperPanel getRaidpPanel() {
        return raid;
    }
}
